import {ReleaseModel} from "../../models/releases.model";
// All available releases. Don't forget to change adastra asb-routing module
export const releasesList: ReleaseModel[] = [
    {
        name: "Mabel",
        url: "mabel",
        majorVersion: 6,
        date: "2024.11.16",
        releaseType: 'recent',
        version: "v6.1.0",
        size: '920MB',
        api: "v6",
        defaultFdrThreshold: '0.05',
        releaseLink: 'https://zenodo.org/records/14174114',
        gtrdExpsPath: "ADASTRA_GTRD_exps.bill_cipher.tsv",
        badMapsPath: "BADmaps.bill_cipher.zip",
        ucscFileName: 'ADASTRA_SNPs.bill_cipher.bb',
        notes: "Concordance annotations are updated for TF SNPs with PWM from HOCOMOCO v12.",
        notesPath: 'readme.mabel.txt',
        tfClArchive: 'adastra.cltf.bill_cipher.zip'
    },
    {
        name: "Bill Cipher",
        url: "bill-cipher",
        majorVersion: 5,
        date: "2022.05.19",
        releaseType: 'deprecated',
        version: "v5.1.3",
        size: '746.4MB',
        api: "v5",
        defaultFdrThreshold: '0.05',
        releaseLink: 'https://disk.yandex.ru/d/LQYSni42Lk0wtg',
        gtrdExpsPath: "ADASTRA_GTRD_exps.bill_cipher.tsv",
        badMapsPath: "BADmaps.bill_cipher.zip",
        ucscFileName: 'ADASTRA_SNPs.bill_cipher.bb',
        notes: "Increased recall of diploid regions. Please find the details in readme.",
        notesPath: 'readme.bill_cipher.txt',
        tfClArchive: 'adastra.cltf.bill_cipher.zip'
    },
    {
        name: "Zanthar",
        url: "zanthar",
        majorVersion: 4,
        date: "2021.09.01",
        releaseType: 'deprecated',
        version: "v4.0.3",
        size: '775.3MB',
        api: "v4",
        defaultFdrThreshold: '0.05',
        releaseLink: 'https://disk.yandex.ru/d/Uwc-uw-sLkfk9g',
        gtrdExpsPath: "ADASTRA_GTRD_exps.zanthar.tsv",
        badMapsPath: "BADmaps.zanthar.zip",
        ucscFileName: 'ADASTRA_SNPs.zanthar.bb',
        notes: "New 'permissive' strategy for BAD calling with simplified 'integer' set of allowed BADs resulting in nearly 2x better ASB calling sensitivity.",
        notesPath: 'readme.zanthar.txt',
    },
    {
        name: "Susan",
        url: "susan",
        majorVersion: 3,
        date: "2021.04.11",
        releaseType: 'deprecated',
        version: "v3.5.2",
        size: '727.5MB',
        api: "v3",
        defaultFdrThreshold: '0.1',
        releaseLink: 'https://disk.yandex.ru/d/YKOdzHeHFVa0Hw?w=1',
        gtrdExpsPath: "ADASTRA_GTRD_exps.susan.tsv",
        badMapsPath: "BADmaps.susan.zip",
        ucscFileName: 'ADASTRA_SNPs.susan.bb',
        notes: "Number of experimental data sets increased from 7668 to 15931, based on " +
            "GTRD v20.06.",
        notesPath: 'readme.susan.txt',
    },
    {
        name: "Soos",
        url: "soos",
        date: "2020.06.22",
        majorVersion: 1,
        defaultFdrThreshold: '0.05',
        releaseType: 'deprecated',
        releaseLink: 'https://disk.yandex.ru/d/8iaZCprOYNLQsQ',
        notes: 'Legacy release described in Abramov et al. doi: 10.1038/s41467-021-23007-0.',
        size: '453.7 МБ',
        version: "v1.6.10",
        api: "v1",
        gtrdExpsPath: "ADASTRA_GTRD_exps.soos.tsv",
        badMapsPath: "BADmaps.soos.zip",
        ucscFileName: 'ADASTRA_SNPs.soos.bb',
        notesPath: 'readme.soos.txt',
    },
];

export const recentRelease: ReleaseModel = releasesList.filter(s => s.releaseType === 'recent')[0];
export const ananastraRelease: ReleaseModel = recentRelease;
