import {ReleaseModel} from "../../models/releases.model";
// All available releases. Don't forget to change app-routing module
export const releasesList: ReleaseModel[] = [
    {
        name: "Bill Cipher",
        url: "bill-cipher",
        majorVersion: 5,
        date: "2022.05.19",
        recent: true,
        version: "v5.0.0",
        size: '775.3MB',
        api: "v4",
        defaultFdrThreshold: '0.05',
        releaseLink: 'https://disk.yandex.ru/d/Uwc-uw-sLkfk9g',
        gtrdExpsPath: "ADASTRA_GTRD_exps.zanthar.tsv",
        badMapsPath: "BADmaps.zanthar.zip",
        ucscFileName: 'ADASTRA_SNPs.zanthar.bb',
        notes: "New 'permissive' strategy for BAD calling with simplified 'integer' set of allowed BADs resulting in nearly 2x better ASB calling sensitivity.",
        notesPath: 'readme.zanthar.txt',
    },
    {
        name: "Zanthar",
        url: "zanthar",
        majorVersion: 4,
        date: "2021.09.01",
        recent: false,
        version: "v4.0.3",
        size: '775.3MB',
        api: "v4",
        defaultFdrThreshold: '0.05',
        releaseLink: 'https://disk.yandex.ru/d/Uwc-uw-sLkfk9g',
        gtrdExpsPath: "ADASTRA_GTRD_exps.zanthar.tsv",
        badMapsPath: "BADmaps.zanthar.zip",
        ucscFileName: 'ADASTRA_SNPs.zanthar.bb',
        notes: "New 'permissive' strategy for BAD calling with simplified 'integer' set of allowed BADs resulting in nearly 2x better ASB calling sensitivity.",
        notesPath: 'readme.zanthar.txt',
    },
    {
        name: "Susan",
        url: "susan",
        majorVersion: 3,
        date: "2021.04.11",
        recent: false,
        version: "v3.5.2",
        size: '727.5MB',
        api: "v3",
        defaultFdrThreshold: '0.1',
        releaseLink: 'https://disk.yandex.ru/d/YKOdzHeHFVa0Hw?w=1',
        gtrdExpsPath: "ADASTRA_GTRD_exps.susan.tsv",
        badMapsPath: "BADmaps.susan.zip",
        ucscFileName: 'ADASTRA_SNPs.susan.bb',
        notes: "Number of experimental data sets increased from 7668 to 15931, based on " +
            "GTRD v20.06.",
        notesPath: 'readme.susan.txt',
    },
    {
        name: "Soos",
        url: "soos",
        date: "2020.06.22",
        majorVersion: 1,
        defaultFdrThreshold: '0.05',
        recent: false,
        releaseLink: 'https://disk.yandex.ru/d/8iaZCprOYNLQsQ',
        notes: 'Legacy release described in Abramov et al. doi: 10.1038/s41467-021-23007-0.',
        size: '453.7 МБ',
        version: "v1.6.10",
        api: "v1",
        gtrdExpsPath: "ADASTRA_GTRD_exps.soos.tsv",
        badMapsPath: "BADmaps.soos.zip",
        ucscFileName: 'ADASTRA_SNPs.soos.bb',
        notesPath: 'readme.soos.txt',
    },
];

export const recentRelease: ReleaseModel = releasesList.filter(s => s.recent)[0];
export const ananastraRelease: ReleaseModel = releasesList.filter(s => s.name === 'Zanthar')[0]
